### ISSUE TITLE
Not working on Unity 2020.3.10f1

### ISSUE THREAD

**Issue by Highcarve** [Unity-Technologies/2d-techdemos#25]
Hello. I used this asset a few months ago when I was learning Unity and it worked just fine. I have attempted to use it now, and I receive the same error every time. 

Assets\Tilemap\Rule Tiles\Rule Override Tile\ExampleSiblingRuleTile.cs(5,39): error CS0246: The type or namespace name 'RuleTile' could not be found (are you missing a using directive or an assembly reference?)

There are a few others of the same ilk. I have attempted to manually add it by the package manager, and when I have attempted that I receive either 
"[Package Manager] Please select a valid package.json file in a package folder. 
UnityEditor.GenericMenu:CatchMenu (object,string[],int)" 

Or

"[Package Manager Window] Unable to add package [https://github.com/Unity-Technologies/2d-techdemos.git]:
  [https://github.com/Unity-Technologies/2d-techdemos.git] does not point to a valid package repository. No package manifest was found. Verify the repository URL and make sure the package is located in the root folder of the repository.
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()"

Please assist.

**Comment by ChuanXin-Unity** [comment]
Hi, in order to make use of the ExampleSiblingRuleTile, you would need to have the 2D Tilemap Extras package installed in your Unity project.

You can get the package from the Unity Package Manager if you are using Unity 2021.1:
![image](https://user-images.githubusercontent.com/29473170/120283803-2d1fdd00-c2ee-11eb-9fc8-242451e0ea32.png)

Otherwise, you can manually add the package through the Unity Package Manager by adding it through a Git Url: https://github.com/Unity-Technologies/2d-extras.git or possibly by name: com.unity.2d.tilemap.extras

If you can share more details, such as which version of the Unity Editor you are using, how you added the above package and the 2d-techdemos project, that would be helpful. Thanks!

**Comment by wacomoto** [comment]
I had the same probelm. Unity 2021.1.9f1. The problem seemed to be with the Tilemap Extras package missing a .git ( I think, I should have noted it down). Removing and reinstalling the package fixed all errors.
